name: Selenium with TestNG - CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Set up Chrome WebDriver
      uses: browser-actions/setup-chrome@latest

    - name: Check Chrome version
      run: google-chrome --version

    - name: Start Xvfb
      uses: robertdebock/xvfb-action@master

    - name: Run Chrome in headless mode
      run: google-chrome --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

    - name: Wait for Chrome to start
      run: sleep 5

    - name: Build with Maven
      run: mvn -B clean test
