name: Selenium with TestNG - CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

 
    - name: Install Google Chrome 

      run: |

              chmod +x ./scripts/InstallChrome.sh

                          ./scripts/InstallChrome.sh 

    - name: Build with Maven

      run: mvn -B package --file pom.xml test

 
    - name: Upload test reports
      uses: actions/upload-artifact@v2
      with:
        name: test-reports
        path: target/surefire-reports
