name: Selenium with TestNG - CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Download Chrome WebDriver
      run: |
        wget https://chromedriver.storage.googleapis.com/latest/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/bin/chromedriver
        sudo chown root:root /usr/bin/chromedriver
        sudo chmod +x /usr/bin/chromedriver

    - name: Check Chrome version
      run: google-chrome --version || (echo "Google Chrome not found, trying to install..." && sudo apt-get update && sudo apt-get install -y google-chrome-stable)
      if: success()

    - name: Run Chrome in headless mode
      run: |
        if ! google-chrome --headless --version &> /dev/null; then
          echo "Google Chrome failed to start, trying to reset..."
          sudo apt-get remove --purge google-chrome-stable
          sudo apt-get install -y google-chrome-stable
        fi
        /usr/bin/chromedriver --version &> chromedriver-version.log
        if ! grep -q "ChromeDriver" chromedriver-version.log; then
          echo "ChromeDriver failed to start, trying to reset..."
          sudo rm /usr/bin/chromedriver
          wget https://chromedriver.storage.googleapis.com/latest/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/bin/chromedriver
          sudo chown root:root /usr/bin/chromedriver
          sudo chmod +x /usr/bin/chromedriver
          sleep 5
        fi
        google-chrome --headless --disable-gpu --remote-debugging-port=9222 --no-sandbox --disable-dev-shm-usage --disable-seccomp-filter-sandbox http://localhost &
        sleep 5
        google-chrome --version &> chrome-version.log
        if ! grep -q "Google Chrome" chrome-version.log; then
          echo "Google Chrome failed to start, trying to reset..."
          sudo apt-get remove --purge google-chrome-stable
          sudo apt-get install -y google-chrome-stable
          sleep 5
          google-chrome --headless --disable-gpu --remote-debugging-port=9222 --no-sandbox --disable-dev-shm-usage --disable-seccomp-filter-sandbox http://localhost &
        fi
      id: chrome-start

    - name: Check Chrome logs
      run: cat chrome-version.log
      if: failure()

    - name: Wait for Chrome to start
      run: sleep 3

    - name: Build with Maven
      run: mvn -B clean test
      env:
        DISPLAY: :99
        NO_PROXY: 127.0.0.1,localhost
