name: Java CI with Maven

on:
 workflow_dispatch:
 push:
    branches: [ "main" ]
 pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: artifacts
      uses: actions/upload-artifacts@v3
      with: 
         name: report
         path: ./reports/*.html
      
      
