name: Selenium with TestNG - CI (or your improved name)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest  # Replace with appropriate runner if needed

    steps:
      - uses: actions/checkout@v3  # Checkout code from repository

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'  # Adjust if necessary
          distribution: 'temurin'  # Or customize distribution
          cache: maven  # Enable caching for efficiency

      - uses: browser-actions/setup-chrome@latest

      - name: Display Chrome Version (Optional)
        run: chrome --version  # Useful for debugging or verification

      - name: Build with Maven (Consider Caching and Failure Handling)
        run: mvn -B clean test

        # Potential Additional Steps:
      - name: Store Test Results (Optional)
        uses: actions/upload-artifact@v3
        with:
            name: test-results
            path: Amazon_POM/src
      - name: Handle Build Failures (Optional)
        uses: actions/github-script@v6
        with:
            script: |
              if (process.env.CI_JOB_STATUS !== 'SUCCESS') {
                core.setFailed('Selenium tests failed!')
              }
